Import common product from Akeneo as Sylius Product
synolia/SyliusAkeneoPlugin pull request #138
Opened 2022-12-15 13:57 UTC by TheGrimmChester

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?   | yes

2022-12-20 09:33 UTC, tuyetrinhvo approved these changes

2022-12-20 16:44 UTC, oallain requested changes
It's a good job, I just put some comments.

2022-12-20 16:44 UTC, oallain commented on .github/workflows/sylius.yaml
> -                if: 'always() && steps.end-of-setup-sylius.outcome == ''success'''
You need to do the same for "Doctrine Schema Validate" line 163.

2022-12-20 16:44 UTC, oallain commented on src/Builder/ProductOptionValueTranslation/MetricProductOptionValueTranslationBuilder.php
> +            'ecommerce'
You need to use ApiConnectionProvider to get the scope.

2022-12-20 16:44 UTC, oallain commented on src/Builder/ProductOptionValueTranslation/MetricProductOptionValueTranslationBuilder.php
> +        $productOptionValue->setValue(\sprintf('%s %s', (float) $data['amount'], $measurable['symbol']));
```suggestion
        $productOptionValue->setValue(\sprintf('%f %s', (float) $data['amount'], $measurable['symbol']));
```

2022-12-23 16:26 UTC, oallain approved these changes

2022-12-23 16:27 UTC, merged